//! The three input feature sets of the `nn-1a298aa575a0` net.
//!
//! Each module provides the same three operations:
//!
//! * `make_index` — the feature index of one (attacker, target, king) tuple;
//! * `append_active_indices` — every index the position activates, for a full
//!   accumulator refresh;
//! * `append_changed_indices` — the indices a move added or removed, for an
//!   incremental update.
//!
//! The index formulas, lookup tables and filtering rules are transcribed from
//! Stockfish 19 verbatim; where a rule looks arbitrary (the `map` table of
//! FullThreats, the half-file mirroring of HalfKAv2_hm) it is because the net's
//! weights were trained against exactly that behaviour, so the tables are
//! generated by `const fn`s from the attack geometry rather than hand-written.

pub mod full_threats;
pub mod half_ka_v2_hm;
pub mod pp_3wide;
